[theme]
primaryColor="#1f77b4"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#262730"
font="sans serif"

[server]
enableCORS=false
enableXsrfProtection=true
maxUploadSize=200
enableStaticServing=true

[browser]
gatherUsageStats=false

[security]
enableXsrfProtection=true
enableCORS=false
enableStaticServing=true 